MQTT Corona Ventilator Web App/api/urls.py
'''
Title: URLS
Version: v1
Date: 14.12.2020

Short Description:
URL Routing for the webapp is set here.
Several URL path are connected to functions from other scripts.

Output Data:

Devices to connect:

Changelog:
14.12.2020 First Test Implementation

'''

##############################################################################
############################### Imports ######################################
from django.urls import path
from . import views

##### Patterns #####

urlpatterns = [
    path('', views.apiOverview, name='apiOverview'),
    path('getConfig', views.configGet, name='getConfig'),
    path('sensor-list', views.sensorList, name='sensor-list'),
    path('sensor-detail/<str:pk>/', views.sensorDetail, name='sensor-detail'),
    path('sensor-create', views.sensorCreate, name='sensor-create'),
    path('sensor-update/<str:pk>/', views.sensorUpdate, name='sensor-update'),
    path('sensor-delete/<str:pk>/', views.sensorDelete, name='sensor-delete'),
    path('patient-list', views.patientList, name='sensor-list'),
    path('patient-detail/<str:pk>/', views.patientDetail, name='sensor-detail'),
    path('patient-create', views.patientCreate, name='sensor-create'),
    path('patient-update/<str:pk>/', views.patientUpdate, name='sensor-update'),
    path('patient-delete/<str:pk>/', views.patientDelete, name='sensor-delete'),
    path('value-list', views.valueList, name='sensor-list'),
    path('value-detail/<str:pk>/', views.valueDetail, name='sensor-detail'),
    path('value-create', views.valueCreate, name='value-create'),
    path('value-update/<str:pk>/', views.valueUpdate, name='sensor-update'),
    path('value-delete/<str:pk>/', views.valueDelete, name='sensor-delete'),
    path('detailValueInfo/<str:patientID>/<str:sensorName>',
         views.valueDetialInformation, name='detailValueInfo'),
]

MQTT Corona Ventilator Web App/main/urls.py
##############################################################################
############################### Imports ######################################

from django.urls import path, include
# views included to  use their functions in urlpatterns
from . import views
from .views import HomeView, PatientDetailView, SearchView, SettingsView

app_name = "main"

urlpatterns = [                                                                 # The `urlpatterns` list routes URLs to views. For more information please see: https://docs.djangoproject.com/en/3.1/topics/http/urls/


    # "" empty path points to HomeView() Function
    path('', HomeView.as_view(), name="homepage"),
    path("patient/<int:pk>", PatientDetailView.as_view(), name='patient-detail'),
    # PK == Primary KEY
    # "register" path points to register function from views
    path("register/", views.register, name="register"),
    # "logout" path points to register function from views
    path("logout/", views.logout_request, name="logout"),
    # "login" path points to register function from views
    path("login/", views.login_request, name="login"),
    path("settings/", SettingsView.as_view(), name="settings"),
    # when just patients is entered -> api.urls is included
    path("api/", include('api.urls')),
    path('search/', SearchView.as_view(), name='search'),
]

MQTT Corona Ventilator Web App/ventilationsite/urls.py
##############################################################################
############################### Imports ######################################

from django.contrib import admin
from django.urls import path, include                                                           # needed to use path() and include()


urlpatterns = [                                                                                 # The `urlpatterns` list routes URLs to views. For more information please see: https://docs.djangoproject.com/en/3.1/topics/http/urls/
    path('', include('main.urls')),                                                             # when just homepage is entered -> main.urls is used
    path('admin/', admin.site.urls),
]

MQTT Corona Ventilator Web App/main/forms.py
'''
Title: main/Apps
Version: v1
Date: 14.12.2020

Short Description:
Webapp forms like register and log in are configurated here.

Output Data:

Devices to connect:

Changelog:
14.12.2020 First Test Implementation

'''

##############################################################################
############################### Imports ######################################
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms


##### Register and Log In Form #####
class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'last_name',
                  'first_name', 'password1', 'password2')

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.is_staff = True
        if commit:
            user.save()
        return user

MQTT Corona Ventilator Web App/main/views.py
'''
Title: main/Views
Version: v1
Date: 14.12.2020

Short Description:
In this script "view functions" are defined which take web request and return
a web response which can be html content or a redirect.

Output Data:

Devices to connect:

Changelog:
14.12.2020 First Test Implementation

'''

##############################################################################
############################### Imports ######################################
# render used to render templates
from django.shortcuts import render, redirect
# HTTP Responses can be used
from django.http import HttpResponse
from api.models import Sensor, Patient, Value
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import Group
from django.contrib import messages
from .forms import NewUserForm
from django.views.generic import ListView, DetailView
from django.db.models import Q
from django.core import serializers
import json
from django.http import JsonResponse


##### Index Page #####


class HomeView(ListView):
    model = Patient
    template_name = 'main/home.html'


class SettingsView(ListView):
    model = Patient
    template_name = 'main/settings.html'


##### Patient Detail #####


class PatientDetailView(DetailView):
    model = Patient
    template_name = 'main/patient_detail.html'

    def get_context_data(self, **kwargs):
        context = super(PatientDetailView, self).get_context_data(**kwargs)
        context['all_objects'] = Patient.objects.all()

        return context


class SearchView(ListView):
    model = Patient
    template_name = 'main/search.html'

    def get_queryset(self):
        query = self.request.GET.get('search')
        object_list = Patient.objects.filter(
            Q(firstName__icontains=query) | Q(lastName__icontains=query)
        )
        return object_list

##### Register field #####


def register(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            group = Group.objects.get(name='Doctor')
            user.groups.add(group)
            messages.success(request, "New Account Created: %s" % username)
            login(request, user)
            return redirect("main:homepage")
        else:
            for msg in form.error_messages:
                messages.error(request, f"{msg}: {form.error_messages[msg]}")

    form = NewUserForm
    return render(request,
                  "main/register.html", context={"form": form})

##### Logout field #####


def logout_request(request):
    logout(request)
    messages.info(request, "Logged out successfully")
    return redirect("main:homepage")

##### Login field #####


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"Your now logged in as {username}")
                return redirect("main:homepage")
            else:
                messages.error(request, f"Invalid username or password")

    form = AuthenticationForm()
    return render(request, "main/login.html", {"form": form})

MQTT Corona Ventilator Web App/main/templates/main/includes/messages.html
{% if messages %}
{% for message in messages %}
  <script>M.toast({html: "{{message}}", classes: "blue rounded", displayLength: 2000});</script>
{% endfor%}
{%endif%}

MQTT Corona Ventilator Web App/main/templates/main/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Ventilation</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link " aria-current="page" href="/">Home</a>
        </li>
        {% if user.is_authenticated%}
        <li class="nav-item">
          <a class="nav-link" href="\admin">{{user.username}}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="\logout">Logout</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Patienten
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% if object %}
              {% for patient in all_objects %}
              <li><a class="dropdown-item" href="{% url 'main:patient-detail' patient.pk %}">{{patient.firstName}}</a></li>
              {% endfor %}
            {% else %}
              {% for patient in object_list %}
              <li><a class="dropdown-item" href="{% url 'main:patient-detail' patient.pk %}">{{patient.firstName}}</a></li>
              {% endfor %}
            {% endif %}
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="\settings">Settings</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="\logout">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link " href="\login" tabindex="-1">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="\register" tabindex="-1">Register</a>
        </li>
        {% endif %}
        {% if user.is_authenticated%}
      </ul>
      <form class="d-flex" method="get" action="{% url 'main:search' %}">
        <input class="form-control me-2" type="search" placeholder="Search" name="search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      {% endif %}
    </div>
  </div>
</nav>